### ISSUE TITLE
global: add ability to set limits

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/helm-georchestra#102]
Limits and requests are useful for limiting the memory consumption of each component: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

For Java apps, this will avoid having to set XMS and XMX as Java supports natively container limits since Java 8: https://stackoverflow.com/a/69321233

**Comment by jusabatier** [comment]
Is there any metrics for each container images needed resources ?
I can work on a PR, but currently don't know default values to use for each app. 

Example : 

values.yaml : 
```yml
    analytics:
      enabled: false
      replicaCount: "1"
      docker_image: georchestra/analytics:latest
      extra_environment: []
      # registry_secret: default
      service:
        annotations: {}
      tolerations: []
+     resources:
+       limits:
+         cpu: 100m
+         memory: 128Mi
+       requests:
+         cpu: 100m
+         memory: 128Mi
```

analytics-deployment.yaml :
```yml
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
+       resources:
+         {{- toYaml $webapp.resources | nindent 10 }}
```

Is this way to do looks good for you ?
