### ISSUE TITLE
add tpl for value substitution

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/helm-georchestra#117]
https://austindewey.com/2021/02/22/using-the-helm-tpl-function-to-refer-values-in-values-files/

Allows to do things like:
```
environment: dev
image: myregistry.io/{{ .Values.environment }}/myImage:1.0
env:
  - name: ENVIRONMENT
    value: “{{ .Values.environment }}”
```
