### ISSUE TITLE
can not configure extra path in ingress

### ISSUE THREAD

**Issue by jeanmi151** [georchestra/helm-georchestra#30]
ref to this PR : https://github.com/georchestra/helm-georchestra/pull/27
I would love to have a way to simply add more path to the ingress to hosts more web apps

**Comment by jeanpommier** [comment]
Adding an additionalHostPaths entry in the hosts section [here](https://github.com/georchestra/helm-georchestra/blob/main/values.yaml#L174) ? like
```

      additionalHostPaths:
        - path: /home/
          pathType: Prefix
          service: wordpress
          portNumber: 80
        - ...
```
