### ISSUE TITLE
Automatic creation of secrets is not used so the helm release apply fails

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/helm-georchestra#62]
The automatic creation of secrets when only the credentials are specified in the values.yaml works great.

But these secrets are not being specified in the different pods, when doing helmfile template I get:
```
- name: PGPORT
  valueFrom:
    secretKeyRef:
        name:
        key: port
        optional: false
```

`name: ` is empty

I think this is due to a logic error inside https://github.com/georchestra/helm-georchestra/blob/main/templates/_helpers.tpl#L75 which never specify the automatically created secrets when using an external postgresql database.
